services:
  vuefrontend-dev:
    container_name: vuefrontendcontainer-dev
    build:
      context: ./vuefrontend
      dockerfile: Dockerfile_dev
    ports:
      - "127.0.0.1:5173:5173"
    expose:
      - "5173"
    volumes:
      - ./vuefrontend:/app
    networks:
      - app-network
    profiles:
      - dev
  
  vuefrontend:
    container_name: vuefrontendcontainer
    build:
      context: ./vuefrontend
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    profiles:
      - prod
  
  goapi:
    container_name: goapicontainer
    build:
      context: ./goapi
    ports:
      - "127.0.0.1:8081:8081"
    expose:
      - "8081"
    networks:
      - app-network
    profiles:
      - prod
    develop:
      watch:
        - action: rebuild
          path: ./goapi
  
  nginx-dev:
    image: nginx:alpine
    container_name: nginxcontainer-dev
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    container_name: nginxcontainer
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
