services:
  vuefrontend-dev:
    container_name: vuefrontendcontainer-dev
    build:
      context: ./vuefrontend
      dockerfile: Dockerfile_dev
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./vuefrontend:/app
    networks:
      - app-network
    profiles:
      - dev
  vuefrontend:
    container_name: vuefrontendcontainer
    build:
      context: ./vuefrontend
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    profiles:
      - prod
  goapi:
    container_name: goapicontainer
    build:
      context: ./goapi
    ports:
      - "127.0.0.1:8081:8081"
    networks:
      - app-network
    profiles:
      - prod
    develop:
      watch:
        - action: rebuild
          path: ./goapi

networks:
  app-network:
