# asd
name: cd-monocontainer

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-to-docker-hub-and-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        run: docker build -t eclairdb_mono . -f ./monocontainer/Dockerfile
        working-directory: ./
      
      - name: Tag and push to Docker Hub
        run: |
          docker tag eclairdb_mono:latest ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Tag and push to Amazon ECR
        run: |
          docker tag eclairdb_mono:latest ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/janharkonen/eclairdb-mono-ecr:latest
          docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/janharkonen/eclairdb-mono-ecr:latest