# asd
name: cd

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-to-docker-hub-and-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build
        run: docker build -t goapi .
        working-directory: ./goapi
      
      - name: Tag and push to Docker Hub
        run: |
          docker tag goapi:latest ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-goapi:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}-goapi:latest

      - name: Tag and push to Amazon ECR
        run: |
          docker tag goapi:latest ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/janharkonen/eclairdb-goapi-ecr:latest
          docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/janharkonen/eclairdb-goapi-ecr:latest
        

  #build-and-push-to-ecr:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v4
#
  #    - name: Login to ECR
  #      uses: aws-actions/configure-aws-credentials@v3
  #      with:
  #        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #        aws-region: eu-central-1
#
  #    - name: Build and push
  #      uses: docker/build-push-action@v6
  #      with:
  #        context: ./goapi
  #        file: ./goapi/Dockerfile
  #        platforms: linux/amd64
  #        push: true
  #        tags: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.eu-central-1.amazonaws.com/janharkonen/${{ github.event.repository.name }}-goapi-ecr:latest